"""Acceptance tests for the target localization + tracking estimation stages.

These tests ISOLATE the TDOA/tracking stages from the other estimators (relative
localization, clock sync) by feeding them TRUTH: the layout is built from the true
device positions and the clocks carry the true offsets/drifts. Acoustic fixtures are
generated by the FROZEN sim leaf function ``generate_acoustic_arrivals`` (importing sim
leaf functions in *tests* is permitted by the contract — only estimation *source* must
not import sim).
"""

from __future__ import annotations

import numpy as np
import pytest

# Frozen estimation contract / shared types (allowed in source and tests).
from dronetracking.datatypes import TargetFix
from dronetracking.estimation.interfaces import RelativeLayout, ClockEstimates

# Modules under test.
from dronetracking.estimation import tdoa, tracking
from dronetracking.estimation.tracking import Tracker

# Frozen sim leaf functions — TESTS may use these for realistic fixtures.
from dronetracking.sim.scenario import Scenario, TrajectorySpec, NoiseSpec, DeviceSpec
from dronetracking.sim.trajectory import trajectory_position
from dronetracking.sim.acoustic import generate_acoustic_arrivals, emission_times

C = 343.0


# --------------------------------------------------------------------------------------
# Fixtures: a non-coplanar ground array so altitude is observable, drone overhead.
# dev0 is the clock reference with true (offset, drift) = (0, 0) per the locked convention.
# --------------------------------------------------------------------------------------

def _devices():
    # Spread in x, y AND z (varied tower heights) so the 3D fix is well conditioned.
    return [
        DeviceSpec("dev0", (0.0, 0.0, 0.0), clock_offset_s=0.0, clock_drift_ppm=0.0),
        DeviceSpec("dev1", (200.0, 0.0, 12.0), clock_offset_s=0.10, clock_drift_ppm=25.0),
        DeviceSpec("dev2", (0.0, 200.0, 8.0), clock_offset_s=-0.07, clock_drift_ppm=-18.0),
        DeviceSpec("dev3", (200.0, 200.0, 20.0), clock_offset_s=0.04, clock_drift_ppm=40.0),
        DeviceSpec("dev4", (100.0, 100.0, 35.0), clock_offset_s=-0.12, clock_drift_ppm=15.0),
    ]


def _scenario(devices, duration=10.0, dt=1.0):
    return Scenario(
        name="tdoa", seed=0, speed_of_sound_mps=C, sample_rate_hz=48000.0,
        duration_s=duration, dt_s=dt, ranging_rounds=10, origin_latlon=(32.0, 34.0),
        devices=tuple(devices),
        # Drone flies high overhead and moves in x and y so geometry varies per emission.
        trajectory=TrajectorySpec("linear", {"start_m": [-40.0, 60.0], "end_m": [260.0, 140.0]}, z_m=120.0),
        noise=NoiseSpec(),  # NOISE-FREE
    )


def _truth_layout_and_clocks(scenario):
    device_ids = scenario.device_ids
    positions = np.array([d.position_m for d in scenario.devices], dtype=float)
    layout = RelativeLayout(device_ids=device_ids, positions_local=positions, covariances=None)
    offsets = {d.id: d.clock_offset_s for d in scenario.devices}
    drifts = {d.id: d.clock_drift_ppm for d in scenario.devices}
    clocks = ClockEstimates(
        device_ids=device_ids,
        offsets_s=offsets,
        drifts_ppm=drifts,
        reference_id=device_ids[0],
    )
    return layout, clocks


def _arrivals_by_emission(arrivals):
    groups = {}
    for arr in arrivals:
        groups.setdefault(arr.emission_idx, []).append(arr)
    return groups


# --------------------------------------------------------------------------------------
# Localization: noise-free arrivals must recover the true drone position to < 1e-3 m.
# --------------------------------------------------------------------------------------

def test_localize_emission_recovers_true_position_noisefree():
    sc = _scenario(_devices())
    layout, clocks = _truth_layout_and_clocks(sc)
    arrivals = generate_acoustic_arrivals(sc, np.random.default_rng(0))
    groups = _arrivals_by_emission(arrivals)
    times = emission_times(sc)

    assert len(groups) >= 1
    for k, group in groups.items():
        fix = tdoa.localize_emission(group, clocks, layout, sc.speed_of_sound_mps)
        truth = trajectory_position(sc, float(times[k]))
        err = np.linalg.norm(fix.position - truth)
        assert err < 1e-3, f"emission {k}: error {err:.2e} m, pos {fix.position}, truth {truth}"
        # Diagnostics must be populated and sane.
        assert fix.n_devices == len(group)
        assert fix.cov.shape == (3, 3)
        assert np.isfinite(fix.gdop) and fix.gdop > 0
        assert fix.residual_rms < 1e-3
        assert fix.t == pytest.approx(float(times[k]) + 0.0, abs=5.0)  # near emission time


def test_localize_all_returns_sorted_fixes_for_every_full_emission():
    sc = _scenario(_devices())
    layout, clocks = _truth_layout_and_clocks(sc)
    arrivals = generate_acoustic_arrivals(sc, np.random.default_rng(1))

    class _Obs:  # minimal duck-typed Observations (only .acoustic is read).
        pass

    obs = _Obs()
    obs.acoustic = arrivals
    obs.speed_of_sound_mps = sc.speed_of_sound_mps

    fixes = tdoa.localize_all(obs, clocks, layout)
    times = emission_times(sc)
    assert len(fixes) == len(times)  # all emissions have all 5 devices (>=4)
    # Sorted by emission time.
    assert all(fixes[i].t <= fixes[i + 1].t for i in range(len(fixes) - 1))
    # Each recovers its truth.
    for i, fix in enumerate(fixes):
        truth = trajectory_position(sc, float(times[i]))
        assert np.linalg.norm(fix.position - truth) < 1e-3


def test_localize_all_skips_emissions_with_fewer_than_four_devices():
    sc = _scenario(_devices())
    layout, clocks = _truth_layout_and_clocks(sc)
    arrivals = list(generate_acoustic_arrivals(sc, np.random.default_rng(2)))

    # Drop devices from emission 0 so it has only 3; it must be skipped.
    kept = [a for a in arrivals if not (a.emission_idx == 0 and a.device_id in ("dev3", "dev4"))]

    class _Obs:
        pass

    obs = _Obs()
    obs.acoustic = tuple(kept)
    obs.speed_of_sound_mps = sc.speed_of_sound_mps

    fixes = tdoa.localize_all(obs, clocks, layout)
    times = emission_times(sc)
    assert len(fixes) == len(times) - 1  # emission 0 skipped


def test_localize_emission_needs_at_least_four_devices():
    sc = _scenario(_devices())
    layout, clocks = _truth_layout_and_clocks(sc)
    arrivals = generate_acoustic_arrivals(sc, np.random.default_rng(3))
    groups = _arrivals_by_emission(arrivals)
    three = groups[0][:3]
    with pytest.raises(ValueError):
        tdoa.localize_emission(three, clocks, layout, sc.speed_of_sound_mps)


# --------------------------------------------------------------------------------------
# Tracking: a constant-velocity trajectory + Gaussian position noise. RMSE small,
# mean NEES in a sane band.
# --------------------------------------------------------------------------------------

def _cv_fixes(rng, n=40, dt=0.5, meas_std=2.0):
    """Synthetic CV trajectory sampled into noisy TargetFix list + the truth states."""
    p0 = np.array([10.0, -5.0, 100.0])
    vel = np.array([6.0, -3.0, 0.5])
    R = (meas_std ** 2) * np.eye(3)
    fixes = []
    truth_pos = []
    truth_vel = []
    for i in range(n):
        t = i * dt
        p = p0 + vel * t
        truth_pos.append(p)
        truth_vel.append(vel)
        noisy = p + rng.normal(0.0, meas_std, size=3)
        fixes.append(
            TargetFix(
                position=noisy,
                cov=R.copy(),
                gdop=1.5,
                residual_rms=meas_std,
                n_devices=5,
                t=t,
            )
        )
    return fixes, np.array(truth_pos), np.array(truth_vel)


def test_track_target_rmse_below_measurement_std_and_nees_sane():
    rng = np.random.default_rng(7)
    meas_std = 2.0
    fixes, truth_pos, truth_vel = _cv_fixes(rng, n=60, dt=0.5, meas_std=meas_std)

    # Near-constant-velocity target -> a small process-noise sigma_a lets the filter
    # smooth aggressively (RMSE well under the measurement std) while staying consistent.
    track = tracking.track_target(fixes, model="cv", sigma_a=0.3)

    assert track.positions_local.shape == (len(fixes), 3)
    assert track.covariances.shape == (len(fixes), 3, 3)
    assert track.velocities is not None and track.velocities.shape == (len(fixes), 3)
    assert np.allclose(track.times_s, [f.t for f in fixes])

    # Filtering should beat the raw measurement noise (skip burn-in transient).
    warm = len(fixes) // 4
    err = track.positions_local[warm:] - truth_pos[warm:]
    rmse = float(np.sqrt(np.mean(np.sum(err ** 2, axis=1))))
    assert rmse < meas_std, f"position RMSE {rmse:.3f} not below meas_std {meas_std}"

    # NEES consistency: mean of e^T P^-1 e over time should sit near 3 (pos dim).
    nees = []
    for i in range(warm, len(fixes)):
        e = track.positions_local[i] - truth_pos[i]
        P = track.covariances[i]
        nees.append(float(e @ np.linalg.solve(P, e)))
    mean_nees = float(np.mean(nees))
    assert 1.0 <= mean_nees <= 6.0, f"mean NEES {mean_nees:.2f} outside [1, 6]"

    # Velocity should converge near truth after warm-up.
    vel_err = np.linalg.norm(track.velocities[-1] - truth_vel[-1])
    assert vel_err < 2.0, f"final velocity error {vel_err:.3f}"


def test_track_target_gates_outliers_with_nis():
    rng = np.random.default_rng(11)
    meas_std = 1.0
    fixes, truth_pos, _ = _cv_fixes(rng, n=50, dt=0.5, meas_std=meas_std)

    # Inject a gross outlier mid-track; NIS gating should reject it.
    bad_idx = 25
    fixes[bad_idx] = TargetFix(
        position=truth_pos[bad_idx] + np.array([500.0, -400.0, 300.0]),
        cov=(meas_std ** 2) * np.eye(3),
        gdop=1.5,
        residual_rms=meas_std,
        n_devices=5,
        t=fixes[bad_idx].t,
    )

    track = tracking.track_target(fixes, model="cv", sigma_a=1.0)
    # The estimate at the outlier step must stay near truth (update rejected).
    err = np.linalg.norm(track.positions_local[bad_idx] - truth_pos[bad_idx])
    assert err < 50.0, f"outlier not gated: error {err:.1f} m"


def test_tracker_class_wraps_track_target_single_target():
    rng = np.random.default_rng(13)
    fixes, truth_pos, _ = _cv_fixes(rng, n=30, dt=0.5, meas_std=1.5)

    tk = Tracker(model="cv", sigma_a=0.3)
    for f in fixes:
        tk.update([f], f.t)  # multi-target seam: a list per timestep, fused to one here
    track = tk.track()

    assert track.positions_local.shape == (len(fixes), 3)
    warm = len(fixes) // 4
    err = track.positions_local[warm:] - truth_pos[warm:]
    rmse = float(np.sqrt(np.mean(np.sum(err ** 2, axis=1))))
    assert rmse < 1.5  # below the 1.5 m measurement std


def test_tracker_rejects_multiple_simultaneous_targets_for_now():
    rng = np.random.default_rng(17)
    fixes, _, _ = _cv_fixes(rng, n=5, dt=0.5, meas_std=1.0)
    tk = Tracker(model="cv", sigma_a=1.0)
    with pytest.raises((AssertionError, ValueError, NotImplementedError)):
        # Two targets at one timestep is not yet supported (association TODO).
        tk.update([fixes[0], fixes[1]], 0.0)
